//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.18408
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMQClient.MSMQServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MSMQServiceReference.IMSMQService")]
    public interface IMSMQService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMSMQService/SendLockMessage")]
        void SendLockMessage(string msg, System.DateTime sendDate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMSMQService/SendToOutputWindow")]
        void SendToOutputWindow(string msg, System.DateTime sendDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMSMQServiceChannel : MSMQClient.MSMQServiceReference.IMSMQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MSMQServiceClient : System.ServiceModel.ClientBase<MSMQClient.MSMQServiceReference.IMSMQService>, MSMQClient.MSMQServiceReference.IMSMQService {
        
        public MSMQServiceClient() {
        }
        
        public MSMQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MSMQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSMQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSMQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendLockMessage(string msg, System.DateTime sendDate) {
            base.Channel.SendLockMessage(msg, sendDate);
        }
        
        public void SendToOutputWindow(string msg, System.DateTime sendDate) {
            base.Channel.SendToOutputWindow(msg, sendDate);
        }
    }
}
